### ISSUE TITLE
Cross-Room Strat Cleanup

### ISSUE THREAD

**Issue by kjbranch** [vg-json-data/sm-json-data#1059]
Due to the increasing number of types of cross-room strats, and the complex ways in which they need to be represented in order to describe in every instance, cross-room strats have become difficult to understand and to implement. 

Cross-room strats are represented in a very different way to in-room strats and to each other, making them difficult to understand by people reading the logic. 
-	`canComeInCharged`: Is a requirement on a strat, which requires either: `canLeaveCharged` on a node in the previous room, a long enough runway at the node in the current room, the adjacent room, or combined between the two rooms.
-	R- and G-mode strats are setup and exit immobile in the nodes, while uses are implemented like normal strats, in the links section.
-	The remaining cross-room strats are only modeled in the second room, while requiring runways in the first room. Adjacent runways have their own sets of problems, such as assuming there are no enemies and making their heat frames hard to interpret.  

The logic implicitly assumes that the system using it can maintain a history of previous nodes traversed through the map, as well as Samus’ states upon room entry. We have been working towards eliminating these, because maintaining cross-room states and previous nodes in the graph traversal of this data is not really possible with its size, and if it were, it would be very computationally intensive. It’s also not very clear how to use the remote setups or remote uses of cross-room shinespark strats. Because of this it is implemented in Map Rando that you have to start the cross-room strat in the destination room. This, and other problems have caused many limitations, such as:
-	Heated room strats require starting from the door, so leaving with speed requires moving away from the door and running back towards it. The heat frames could be reduced if the strat could be started before getting to the door. This is what `initiateRemotely` is attempting to fix.

All of the examples in Crateria that I can think of:
-	Landing Site: Using a shinespark to break the blocks to the Gauntlet Entrance, and then sparking through the door.
-	Parlor: Using g-mode artificial morph to crystal flash, damage back down, then break the blocks to the top left door to bring in a Geemer to setup g-mode going left.
-	Parlor: Using speed to break the blocks and leave through the left door with speed.
-	Gauntlet Entrance: Using Speed or artificial morph to break the blocks, releasing the Waver, to then use for a G-mode setup on the same or opposite door.
-	Gauntlet Entrance: Use speed to break the central blocks, making a runway that can be used to spark out the opposite door.
-	Gauntlet E-Tank: Come in with speed or g-mode, break the left blocks to make a larger runway to go out with after farming.
-	Climb: Break the bomb blocks then use the full runway and the adjacent room’s by running out of the door.
-	Climb: Run in from the left, through the bomb blocks, then Behemoth Spark without losing speed.
-	Green Pirate Shaft: Using G-mode to get up to the Beetoms, to then use to leave with G-mode Immobile on a different door.

**Comment by blkerby** [comment]
Yeah, just to highlight, the main problem here is a general inability to represent cross-room strats that begin at a node other than the door node going out. Solving this will require some work and result in breaking changes, but I think it's worth doing because of the large number of cases where this limits us and/or causes logic unsoundness. Another example just came up this morning on the Discord: using the runway in the top of Etecoon Energy Tank Room to get a shinecharge and carry it out the bottom-left door; this is a case where the logic is currently unsound because it does not include the requirements needed to get from the bottom-left door to above the crumbles.

In the case of "canLeaveCharged", I think "initiateRemotely" was intended to be used to express strats like that. However, it hasn't been used consistently in the data (and Map Rando doesn't consume it), it has quite a complex schema, and it wouldn't provide a full solution since it only applies for this one type of cross-room strat ("canLeaveCharged"), whereas we would like to be able to specify a source node on any type of cross-room strat.

To me, currently the most promising solution would be to move cross-room strats out of special node properties (e.g. "canLeaveCharged", "leaveWithGModeSetup", etc.) and into "links" with the rest of the strats, where naturally both a "from" and "to" node can be expressed. Having these be represented as ordinary strats will also make them easier to consume by systems that use this data: in Map Rando for instance, such strats will then automatically show in the logic pages (and filtering by "from" and "to" nodes will work as expected), and the notable strats will function properly as notables. Here will need to add some properties at the strat level to express effects of cross-room strats that exit the room, or other-room requirements of cross-room strats that enter the room. If the overall idea here sounds good, I can take some time to flesh out a detailed proposal of what this could look like.

**Comment by osse101** [comment]
Making use of existing strat logic is much better than door->start node->back to door.

Specifying a source node for all `canLeave` type strats makes a lot of sense.  I guess originally, maybe, you could freely traverse to the runway, but the variety of strats are a lot more complicated now.  Every heated room would need a source node to be more accurate with heat frames.  Given a source node and door node, they could be written in Links with the other strats.  
For code organization, its not really helpful to keep farms/GmodeSetup/canLeaveCharged separate.  canLeaveCharged setups are getting more involved and strat-like.  Runways and jumpways are more physical descriptions of the terrain connected to the door node though.

I guess this would be through adding more strat properties.  GModeImmobile would look weird with `LeaveWithGModeSetup`->`ResolveImmobile`->`GMode Strat`.  Not that the order of events is any different, but its a conditional start to a strat and a restricted end of strat state.  

Cross room strats following a node path through Links is a good thing to work towards.  You could probably make the current structure work with an additional Starting Point indicator.  But that sounds like extra object handling, and some of these strats just include travelling multiple nodes, which should be kept in Links.

**Comment by blkerby** [comment]
Yeah, runways are one of the trickiest ones to think about. As we have them now, runways are kind of more than just physical descriptions of terrain because they can also have requirements (e.g. to take heat damage or to clear enemies or other obstacles in order to use them); we are "overriding" those requirements in some cases (e.g. for X-ray climb setups) which seems awkward and likely to lead to logic unsoundness, e.g. in cases such as Mickey Mouse Room bottom left door where runway requirements should not be overridden. Because of how runways contain requirements, they are already strat-like in some cases, and maybe it would make sense to fully convert them into strats following the same proposed pattern as other cross-room strats. The thing with runways though is that there are so many ways they can be used, including
- to begin a short-charge that is completed in the next room
- to complete a short-charge that is carried into the next room
- to shinespark through the transition into the next room
- to gain momentum for a jump that happens in the next room
- to gain momentum to jump through the door
- to set up getting stuck in closing door of the next room, for X-ray climbs

To have to write a separate strat for each of these cases on every runway would seem unacceptably wasteful/redundant. On the other hand, in theory there could be scenarios where the requirements are not all the same between these different cases, so we might want to allow flexibility to restrict a runway strat to a specific subset of these uses. A dumb example is that heat frames will be slightly different if a runway is used for a short charge vs. for gaining speed (there are further complications that can affect heat frames, e.g. how much space is available for completing the short charge in the next room or if a specific amount of speed is needed through the transition). In general, details this small are probably not worth the trouble of modeling them. Still it might be worth thinking about, to set up the schema in a such a way that could leave us an option to model such differences if they turn out to matter in some cases.

For the purposes of the initial restructuring, my inclination would be to change where runways go but to leave their semantics unchanged. I.e. instead of a "runways" node property and "adjacentRunway" logical requirement, we would have "leaveWithRunway" and "comeInWithRunway" strat properties, but they would behave the same in terms of how they are matched (likewise "leaveWithRunway" would match with a "comeInCharged" strat property). I think we could later follow up to refine how these work, hopefully eliminating the need for requirement overrides and addressing any remaining soundness issues.

**Comment by kjbranch** [comment]
The cross-room strat structure has been implemented, and a large amount of the project has been completed. There are still strats that need to be migrated, particularly G-Mode, and new types cross-room strats that need to be included, such as coming in with blue space, etc. This issue is closed for now, and new issues can be included as needed.
