### ISSUE TITLE
Tech: canCrumbleQuickDrop vs canQuickCrumbleEscape

### ISSUE THREAD

**Issue by kjbranch** [vg-json-data/sm-json-data#1540]
There was some discussion of adding `canCrumbleQuickDrop` or renaming `canQuickCrumbleEscape` to it, while potentially slightly changing its use to only focus on the drop portion of the strat (in #463). This tech could then be expanded to uses like quickly falling through a crumble block while moving with a shinecharge timer.

There was some discussion about `canQuickCrumbleEscape` representing being stuck on a failed attempt, and it being more useful in representing the Mickey Mouse Multiviola ice clip's crumble escape, where `canCrumbleQuickDrop` wouldn't apply.

Would it be best to have `canCrumbleQuickDrop`, `canQuickCrumbleEscape`, or both?

**Comment by osse101** [comment]
I see `canQuickDrop` being the community name for the technique and `canCrumbleQuickDrop` is a bit of a nicer name.  `canMomentumConservingTurnaround` was something I tried to attach to falling down opening doors, but a quick drop is the same movements.  And quick dropping on top of actively breaking blocks is another case that saves frames that maybe matters somewhere; it's done on the upper left door runway of red tower in any% while waiting for a bomb to explode.

The ability to reliably quickDrop is about very hard.  The value of the tech is that it saves a decent number of frames.  And in those situations there tends to be additional factors which make the strat difficult.  early supers room has the softlock risk, mission impossible has the softlock risk, early supers shinespark is a room reset, etecoon etank is a one way.  `Early Supers Quick Crumble Escape` could be moved to `Very Hard` really and I don't think there needs to be a notable made because it is still closely tied to the general tech.

Rejumping through the crumble block in mickeymouse and etecoon-main-shaft seems unrelated to quick dropping.  Its kinda more of a canQuickRejump tech like canBombJumpWaterEscape.
