### ISSUE TITLE
Spark through door number of frames

### ISSUE THREAD

**Issue by kjbranch** [vg-json-data/sm-json-data#670]
Sometimes it may be necessary to spark through a door for a strat, such as getting through the top door in Mt. Everest. 
- We need a way to represent shinespark frames used in the next room.
- Is this only a scenario for vertical doors, or do horizontal doors need to be considered?
- Currently this Mt. Everest example is simply to avoid a gravity jump, so this could be very low priority, but there may be other examples.

**Comment by osse101** [comment]
Oh I see the problem, there is like a forced `comeInCharged` going on.
For most doors you can crash into the door then open it, so this only applies to doors where you would otherwise fall after and be unable to get back up.  Which would also likely mean two sparks are happening to open the door and to go through.

There's aren't too many rooms with a long runway underneath.  Crocs room you can't naturally jump to, but a speed jump or walljump can reach.
Hypothetically in screw attack room you could open the door with wave and diagonal spark through, except you can open the door after the spark already.
Ridley's room doesn't have the angle or time.
Fish tank doesn't have a runway.

So I can't think of any other rooms this is a problem for.  Spikesuit might be able to open up some options.
