### ISSUE TITLE
Room Diagram Colors

### ISSUE THREAD

**Issue by kjbranch** [vg-json-data/sm-json-data#744]
Should we add new colors or line types for different types of nodes and links?
- Nodes: 
  - Utility, 
  - Event
- Links: 
  - SpawnAt,
  - Possibly cross room strats that bypass junctions: x-ray climb, shinespark, cross room jump?
  - Are G-Mode links still worth neglecting?
  
What would we do if there are multiple types of links that go between two nodes (i.e. a SpawnAt and normal link)?

**Comment by osse101** [comment]
I was wondering if you still wanted to reduce node count by merging utility, event, or doors with junctions.  Or maybe just in part.

```
"door", "entrance", "exit", "event", "item", "junction", "utility"
```
and
```
GMode Junction, Obstacle, Lock
```

I think I'd like entrance+exit to be different from door.  
Junction / utility / the rest are fine as they are.  If we wanted to be proper, they could all be different.  But it looks alright.

Spawnat should have a different arrow then normal links.  I'm feeling green or purple.  If there is a spawnat and a normal link then the normal link is all that needs to be shown.  The arrows will give enough information about how players can move through the room.

Direct link arrows would be nice.  I could see them making it more readable.  Because the remaining normal arrows would indicate normal movement through a room.

GMode is still too much clutter.  A minimalist GMode mark could be added.  Not sure how helpful that would be.
Notes around the doors could be ok for marking enemies.  I'm not sure how necessary that information is, but it'd be neat.
A fully functional model would note all the breakable blocks.
A duplicate room diagram for GMode links could show everything.  And maybe more appealing with minnie's work on separating diagrams.
It is also the case that the majority of links have a map relevant obstacle being bypassed, or just gain artificial morph.  Its the big rooms that have multiple gmode strats, and those have bigger room diagrams to draw on.
