### ISSUE TITLE
Add very low level tech

### ISSUE THREAD

**Issue by kjbranch** [vg-json-data/sm-json-data#745]
Is it worth adding very low level tech? These need not be toggleable, and therefore strats missing them aren't as bad. What are the benefits of adding them?
- `canMidAirMorph`

These could go towards implementing flash/blue suit strats in the future:
- `canVerticalJump`
- `canDash`

We currently have some helpers/items for equipment that are not currently toggleable. Should they be deleted if/until we add them to the logic?
- `h_canShoot`
- `PowerBeam`
- `PowerSuit`

**Comment by osse101** [comment]
I want very low level techs as a reference as to what can be expected mostly.  Which could mean they don't need to be added, just described.  But adding them  would better define existing tech expectations.  But particularly where users ask questions about the low level tech.

`canMidAirMorph`  is bounded by `can3HighMidAirMorph`.  Underwater the only other tech is R-Jumps, so if you can stand in water you are expected to jump morph.
`canTurnAroundSpinJump`  has been very strange.  Its not super well known but is a good way to normalize jumps and is particularly good underwater.  Also for escaping water when the water level is low but still interfering with jumps.
`canBufferedJump` overlaps with `canCrumbleJump` a lot.  In other uses it might already be called `canTrickyJump`.
`canScrollCamera` is close to being a tech.  Jumping to fix the camera.  Aim down (or morph) so it scrolls a little bit more.  Moonwalk.  Run from side to side.
 `canEscapeDraygonGrab`
 `canStopOnADime`
 `canGrappleFling`
 `canXRayBuffer` for something like waiting for snails to position for snail clip.
 `canPirateHide` has started popping up as a way to fight Space Pirates without them firing back.
 `canDespawnProjectile`
 `canDisableEquipment`

**Comment by osse101** [comment]
`canVerticalJump` The majority of that time can check for `canCrouchJump`.  Blue suit would have a little extra `canWaitThreeSecondsThenVerticalJump`

`canDash` looks awful to add.  But its possibly not as bad as first impressions would seem, aside from HeatFrames.

`h_canShoot` Probably should go.  It's a little misnamed too since missiles, grapple, and SBAs could be considered shooting.
`PowerBeam` and `PowerSuit` can stay but I suppose only because it feels cozier to have a complete inventory list.

**Comment by miketrethewey** [comment]
I find some of the more-dexterous techs to be difficult and things like `canMidAirMorph` are part of that. Making it a parent tech to the others (if it isn’t already) would be where it would go. 
`canDash` would be just `Speed`? And probably a runway requirement?
`canVerticalJump` would be a space (physical space) requirement? Or is it vertical Sparking?
`h_canShoot` and `PowerBeam` were for Beamless. The hack is doable (set short distance to 0) and would be a companion to Z3’s Swordless.
`PowerSuit` in case some functionality wanted to be removed there somehow. It’s for completeness since the model is also supposed to describe game state. That would include starting inventory.

**Comment by osse101** [comment]
`canPseudoScrew`
`canSpecialBeamAttack`

For `canDisableEquipment` I had suitless maridia in mind, but it's also pretty common to turn off speed instead of knowing to release dash.  And I think I prefer Disabling speed to a `canHJBlessSpeedMovement` tech.
