### ISSUE TITLE
How and when to use enemyKill

### ISSUE THREAD

**Issue by kjbranch** [vg-json-data/sm-json-data#849]
I wanted to have a discussion about when and how to use enemy kill strats in the logic. I was talking to Maddo and we had fairly different ideas about it at first.

The discussion was prompted about adding `canPseudoScrew` on the `useRequires` of the weapon `PseudoScrew`, seen in #846.

If there is a strat in logic to kill a pink space pirate with pseudo screw, which of these options should the logic show: 
1. 
```
{"enemyKill":{ "enemies": [ [ "Pink Space Pirate (standing)" ] ] }}
```
2. 
```
{"enemyKill":{ "enemies": [ [ "Pink Space Pirate (standing)" ] ],
    "explicitWeapons": [ "PseudoScrew" ]
}}
```
3. 
```
{"enemyKill":{ "enemies": [ [ "Pink Space Pirate (standing)" ] ],
    "explicitWeapons": [ "PseudoScrew" ]
}},
{ "enemyDamage": { "enemy": "Pink Space Pirate (standing)", "type": "contact", "hits": 1 } }
```
4. 
```
"canPseudoScrew",
"Charge",
{ "enemyDamage": { "enemy": "Pink Space Pirate (standing)", "type": "contact", "hits": 1 } }
```

The `enemyKill` is very complex and hard to know what is going on behind the scenes for players reading the logic. It is also very complex to implement correctly. It is also computationally intensive if implemented correctly and could slow seed generation down.

[2] and [3] are simple and clear what is going on, but it is likely not instantly obvious to the player that they will take a hit from the pirate (at least in [2]), as pseudo screw doesn't kill the enemy in one hit. Should the logic imply that a randomizer needs to look up if the enemy is killable in 1 hit and if not apply a contact hit, as so [2], or should the strat itself add that [3]?

[4] avoids the enemy kill, making the logic more direct and easier to compute, but it does lose the enemy name and may be less clear what the player is doing in this strat. This would require more detailed strat titles and descriptions.

One option is to not use `enemyKill` on strats where the weapon has the property `"situational": true`. This is probably a good rule, but the same argument can be made about other situations. For instance should the blue hoppers in Tourian say 
```
{"enemyKill":{ "enemies": [ [ "Blue Sidehopper", "Blue Sidehopper" ] ], 
    "explicitWeapons": [ "Super" ] 
}}
``` 
or 
```
{"ammo": { "type": "Super", "count": 10 }}
```

**Comment by blkerby** [comment]
My opinion is that `enemyKill` is a sledgehammer that would be best to only use where the complexity inside it is actually useful (i.e., where we want many alternative ways of killing the enemy to be automatically considered). Otherwise option 4 seems better. I don't think losing the enemy name is a problem, because the purpose of `requires` is to describe logical requirements to do a strat, not to describe exactly what happens in a strat (which can be spelled out in a "note" or "devNote" if it is not clear from the strat name). Interested to see what others think.

**Comment by osse101** [comment]
I'm pretty sure the idea of `enemyKill` is to let you change the damage values of beams/ammo and have it apply everywhere.  Otherwise we are calculating costs that could have been written directly into logic.

I think right now enemyKill only gets ammo costs.  But health is another resource it could figure out applying only to pseudo screw.  It can figure out how long it takes to kill an enemy but we can't use that in logic for heat frames, canBePatient, or if the enemy can be killed before reaching Samus.  And that would add to the processing time.

<details>
  <summary> Just for Fun</summary>
Maybe there could be a slowEnemyKill object to replace the stack of spazer only, missile only, Charge only strats. 

```json
{"slowEnemyKill: {
  {"enemyKill":{ "enemies": [ [ "Pink Space Pirate (standing)" ] ] }},
  "threshold": 1000 
}
```
</details>

I don't know that we can tell schema what the connection between the weapons and enemies tables is to make it more efficient.

Listing health cost as a requirement when reading the logic would be good.  I wonder if we have all the pseudo screw enemyKills showing health costs right now 🤔 It could get harder to read with health and damage numbers changed if health cost was attached to every use 🙄 

`canPseudoScrew` probably means you know it is possible to take damage when the hit doesn't kill.  It's a little less required to know how much the enemy will hit back for, that would take multiple playthroughs.  And it shouldn't be required to know the damage of pseudo screw and the health of the enemy.

**Comment by blkerby** [comment]
Changing the damage values of beams/ammo would have a lot of consequences which `enemyKill` would not be able to handle. For example, it would affect heat frames required, and certain time-sensitive strats would become impossible: for instance, freezing the fish while falling into Fish Tank or doing a cross-room jump up into Main Street. So I doubt that this can work properly, at least not without a larger overhaul of how enemy interactions are modeled. Personally I don't find modifying beams/ammo to be a very interesting idea for a randomizer anyway.

**Comment by fdtaillefer** [comment]
`enemyKill` (alongside `enemyDamage` was part of a design intent to avoid as much coupling to vanilla values as possible, much like `weapons` themselves. Not just for weapons but also for enemy stats. It was also an attempt to avoid listing an exhaustive list of ways to kill each enemy.

Things like heat frames could probably be handled fairly well since weapons also come with cooldowns so it's already possible to calculate the time to kill while spamming any weapon. A `timeBetweenShots` could also possibly handle more unusual circumstances.

It's true that several strats that interact with enemies likely make other assumptions that don't have logical elements to represent them, maybe a `maxTimeFrames` property could address some of that (i.e., you can't fulfill the `enemyKill` if you can't kill the enemies in that time).


I don't know whether any of that aligns with the current design goals of the project. I will mention the possibility of precalculating some things in the model to take away some of the calculations that are unnecessary if the weapon/enemy stats never change, with the intent of generating a simplified model that can be used as the real input for seed generation by a project.

**Comment by kjbranch** [comment]
We have started using enemyKill slightly more often, but it is nowhere near a point where enemy properties can be adjusted and it be relied upon. 

It looks like this project has mostly focused on representing the vanilla game with extreme accuracy, rather than focusing on easily being able to customize properties like mentioned. If those were focused on instead, that would require a major overhaul throughout, not only for enemyKill.
