### ISSUE TITLE
More Ice strats

### ISSUE THREAD

**Issue by blkerby** [vg-json-data/sm-json-data#973]
Add a couple Ice strats that are missing:
- Big Pink: Freeze a Zeb to clip up through the crumble blocks. Bobbob mentioned it can also be done with a Reo, allowing for a G-mode setup through the door.
- Boyon Gate Hall: Using ice to get through the gate, assuming this is humanly viable? I remember seeing this somewhere but don't know how it works (some kind of wall ice clip using a Zebbo?)

**Comment by osse101** [comment]
Boyon Gate Hall was very TAS only but Bob probably has been able to do it since I last looked at it.  It should take a normalized start to setup subpixels.  Then frame perfect freeze on the bug plus a frame perfect jump and mockball to clip into the gate enough for it to auto raise.  
I want to say there is a way to shoot the green button too, using pause buffers.
It does use wall ice clip tech.

**Comment by osse101** [comment]
Big Pink: Freeze a Zeb
Joonie was doing it by simply counting the passage of time for the first unfreeze, since that wat the part that seemed hardest to me.  
You transition from crouch to standing as the zeb reaches Samus' height so that it moves when between the two heights, on the correct vertical pixel.  Freeze it with spazer or wave + ice.  Then wait below the crumbles, keeping the hidden bug on screen when it unfreezes, and freeze it again below the crumbles for the clip.

Big Pink: Freeze a Reo
It looked like you want to use very scripted movements to jump with the reo at the right time, or it will not make it up to the crumbles but instead get caught on a different piece of ceiling.

**Comment by osse101** [comment]
- Big Pink: Freeze a Zeb that is inside of the crumble blocks leading to Mission Impossible top, and run into it to clip into the crumbles, destroying them. https://clips.twitch.tv/BombasticTangentialPenguinDancingBaby-Ody4XhfLSXIB0B71

**Comment by osse101** [comment]
Zeb clip: https://vimeo.com/807526377
Reo clip: https://vimeo.com/807337618

**Comment by osse101** [comment]
Boyon Gate Hall appears to still be PAL only
