### ISSUE TITLE
East Sand Hole suitless instant morph

### ISSUE THREAD

**Issue by blkerby** [vg-json-data/sm-json-data#987]
With HiJump (suitless) you can wall jump back and forth between the walls and then instant morph in the right place to get up to the right-side item. Looks like it's pretty precise but not sure exactly what the tech should be. I assume it might be easier than underwater walljumping on the single wall (the current strat in logic with these items)?

https://clips.twitch.tv/ElatedPlacidManateePRChase-MH8jSDTFWSOzctCl

**Comment by osse101** [comment]
I didn't think that was possible

**Comment by osse101** [comment]
I still can't get it but it looks like a max delayedWalljump with an instant-instant morph, which is a 2highwalljumpmorph.  The hard part is getting your hitbox just right so you don't bump the crumble blocks.

I could be possible that underwaterwalljump style movements can position you properly on the right wall (because your hitbox will be smaller) and from there morph into the hole.

```
canInsaneWalljump
canConsecutiveWalljump
canSuitlessMaridia
canPlayInSand
can2HighWallMidAirMorph
HiJump
```
